### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by anhuaxiang** [milvus-io/milvus-insight#102]
**Milvus-insight version:**

**Milvus version:**

**Browser version:**

**Browser OS version:**

**Describe the bug:**

**Steps to reproduce:**
1.
2.
3.

**Expected behavior:**

**Screenshots (if relevant):**

**Errors in browser console (if relevant):**

**Provide logs and/or server output (if relevant):**

**Any additional context:**

麻烦看下这个，是不是bug
#101

**Comment by shanghaikid** [comment]
fixed.
