### ISSUE TITLE
terminology: schema or structure?

### ISSUE THREAD

**Issue by congtan0224** [milvus-io/milvus-insight#104]
I would like to know, schema or structure, which one is more clear when using a database product?

**Comment by shanghaikid** [comment]
I think we should stick with schema, since milvus is using it. many thanks for mentioning it. lets change it to schema.

**Comment by shanghaikid** [comment]
and we should change rows to entities as well.

**Comment by Tumao727** [comment]
@shanghaikid `row count` should also be changed as `entity count`?
