### ISSUE TITLE
Feat: Add view code mode for modals

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#143]
**Describe the feature:**
As a user, he can view coding block about the operation that GUI does. 

For example, 

when I create an index, I can see how to do it in Python/GO/node SDKs. 
when I do vector search, I can see how to do it in Python/GO/node SDKs. 
...

**Comment by congtan0224** [comment]
why vector search need code mode? In my opinion, the search console we just removed before is the same thing like the code mode.

**Comment by shanghaikid** [comment]
> why vector search need code mode? In my opinion, the search console we just removed before is the same thing like the code mode.

That's different thing, the thing we removed was using DSL based search, which is a restful console. 

The code mode means that user can view the current command used to execute the GUI action.  
For example,  create a IVF index,  or create a partition.  

I mean the code mode can be a global view.  but we can just apply it to the index creation process.

**Comment by congtan0224** [comment]
<img width="447" alt="Screen Shot 2021-07-30 at 2 36 42 PM" src="https://user-images.githubusercontent.com/77377414/127611266-87b77052-0a3c-46d2-8feb-c1c3658b1b2e.png">
