### ISSUE TITLE
Feat: show created time on collection/partition page

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#144]
**Describe the feature:**
Milvus insight should display created time on collection/partition table. 

Format: 2021-04-13 08:41:34.51+00

**Comment by shanghaikid** [comment]
depends on https://github.com/milvus-io/milvus/issues/6692

**Comment by nameczz** [comment]
Need to wait for milvus-rc3 published

**Comment by congtan0224** [comment]
<img width="681" alt="Screen Shot 2021-07-29 at 9 53 34 AM" src="https://user-images.githubusercontent.com/77377414/127419281-e5514994-b7d8-4d8a-aa62-133d34c3da77.png">

**Comment by shanghaikid** [comment]
done.
