### ISSUE TITLE
Feat: Show index building progress for collection

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus-insight#150]
**Describe the feature:**
1. We can get how many datas already build index.
2. Through websocket.

**Describe a specific use case for the feature:**
Let user know their index building progress.
When data is large , it will be helpful

**Comment by congtan0224** [comment]
<img width="673" alt="Screen Shot 2021-07-29 at 9 52 02 AM" src="https://user-images.githubusercontent.com/77377414/127419190-9b8d2edf-7250-4ca7-b154-eda7526981d2.png">

**Comment by congtan0224** [comment]
<img width="733" alt="Screen Shot 2021-07-29 at 3 03 47 PM" src="https://user-images.githubusercontent.com/77377414/127446973-30b33991-2b72-403b-bb51-8dc217d19187.png">
