### ISSUE TITLE
Feat: Add Community popup

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#166]
Feature describe:

We want our user to reach us easily, so adding more channels is the way to go. 

Add a button like this on the page,
![image](https://user-images.githubusercontent.com/185051/126971540-1023426d-aa8c-4ab9-a3d0-68ea4ea5e401.png)

on a popup, there should be 
Title: Our growing milvus community is here
LEFT PART:  the QR code image
RIGHT PART: 
Have question about milvus ?
- Scan QR code to get access 
- Join our growing social community today
- Get insight, tips and share ideas

**Comment by congtan0224** [comment]
Except for scanning QR code, can user click the other two items? How to join the community and get insight, where would this refer user to?

**Comment by shanghaikid** [comment]
> How to join the community and get insight, where would this refer user to?
We will have a link like https://slack.milvus.io

**Comment by congtan0224** [comment]
<img width="399" alt="Screen Shot 2021-07-29 at 5 30 02 PM" src="https://user-images.githubusercontent.com/77377414/127468195-b1ddc3b3-3d31-44c0-8abb-2364dfefebc4.png">

**Comment by Tumao727** [comment]
completed by #217
