### ISSUE TITLE
Vector search: got unexpected Error when the dimension is different

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#168]
![image](https://user-images.githubusercontent.com/185051/127080064-5d973758-74d8-4f2c-a6e7-5d320339e84a.png)

- give user more clear tips about the dimension 
- check dimension before search

**Comment by nameczz** [comment]
Will also check in sdk https://github.com/milvus-io/milvus-sdk-node/issues/20.
