### ISSUE TITLE
连接milvus的时候报network error

### ISSUE THREAD

**Issue by aixuedegege** [milvus-io/milvus-insight#178]
**Describe the bug:**
登陆界面连接milvus的时候报network error
但是想用insight，

**Steps to reproduce:**
1.在服务器（111.111.111.111）用k8s安装的，方法在这里https://milvus.io/cn/docs/v2.0.0/install_cluster-helm.md。
2.目前能够正常的用python在本地访问milvus
3.选择一台命令 docker run -p 8123:3000 -e HOST_URL=http://127.0.0.1:8123 -e MILVUS_URL=111.111.111.111:19530 milvusdb/milvus-insight:latest
进入界面milvus-insight点击连接，就报错了

**Milvus-insight version:**
milvusdb/milvus-insight:latest

**Milvus version:**
v2.0.0

**Comment by nameczz** [comment]
HOST_URL need to be you machine ip which run your milvus-insight docker. 

I think maybe it's http://111.111.111.111:8123 in your condition.

Also we will update our readme to make it more clear.

**Comment by aixuedegege** [comment]
tks a lot. According to your suggestion, my problem has been solved perfectly.
