### ISSUE TITLE
Feat: add loading state for this page

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#200]
![image](https://user-images.githubusercontent.com/185051/127979029-7560c45b-22c1-4610-b069-19315c2878b7.png)

We can't guarantee the connection speed between the server and the milvus cluster.  

So we need the loading state for this page.

**Comment by congtan0224** [comment]
Does a collection need loading status? or this page?
My solution so far is to add loading status for the single collection and also provide users with a notification...
<img width="446" alt="Screenshot 2021-08-10 at 08 34 27" src="https://user-images.githubusercontent.com/77377414/128829037-01139fdd-4e4f-4939-a493-9496abc9c099.png">

**Comment by shanghaikid** [comment]
This page has 4 parts of data to load. I think each part needs a loading indicator.  
we can just showing a loading indicator telling user that the page/data is loading. no need to send notifications.
