### ISSUE TITLE
Cannot POST /127.0.0.1:8000/api/v1/milvus/connect

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus-insight#204]
**Describe the bug:**
When click Connect button, the dialog reports the message "Cannot POST /127.0.0.1:8000/api/v1/milvus/connect"
![image](https://user-images.githubusercontent.com/12268675/128144419-255fa02d-f16e-4849-a986-86744254e82c.png)

Then I go to dev mode, find that `connect`'s Request URL is ` http://127.0.0.1:8000/127.0.0.1:8000/api/v1/milvus/connect
 `. I guess it should be `http://127.0.0.1:8000/api/v1/milvus/connect`. But I try a post request as follow, it still failed.
```
post http://127.0.0.1:8000/api/v1/milvus/connect
body
{
  "address": "127.0.0.1:19530"
}

response
{
  "statusCode": 400,
  "message": "Error: Connect milvus failed, check your milvus address.",
  "error": "Bad Request"
}
```
However, I can run `hello_milvus.py` successfully.

**Steps to reproduce:**
1. deploy milvus using docker-compose follow by https://milvus.io/docs/install_standalone-docker.md
2. run command `docker run -p 8000:3000 -e HOST_URL=127.0.0.1:8000 -e MILVUS_URL=127.0.0.1:19530 milvusdb/milvus-insight:latest`
3. open `127.0.0.1:8000` in the browser, click `connect` button

The information about docker ps
```
$docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                    PORTS                                           NAMES
f828d6535006   milvusdb/milvus-insight:latest   "/bin/bash -c '/app/…"   47 minutes ago   Up 47 minutes             0.0.0.0:8000->3000/tcp, :::8000->3000/tcp       stoic_pascal
78b701884e49   8938d19d0313                     "/tini -- milvus run…"   53 minutes ago   Up 53 minutes             0.0.0.0:19530->19530/tcp, :::19530->19530/tcp   milvus-standalone
e2b1dcf9a7f6   61ad63875109                     "etcd -listen-peer-u…"   53 minutes ago   Up 53 minutes (healthy)   2379-2380/tcp                                   milvus-etcd
3a69db060801   b849e0c26c4c                     "/usr/bin/docker-ent…"   53 minutes ago   Up 53 minutes (healthy)   9000/tcp                                        milvus-minio
9a12aadf0c92   registry:2                       "/entrypoint.sh /etc…"   25 hours ago     Up 25 hours               0.0.0.0:5000->5000/tcp, :::5000->5000/tcp       kind-registry
```

**Milvus-insight version:**
latest

**Milvus version:**
latest

**Comment by nameczz** [comment]
You can try to replace 127.0.0.1 with your computer ip.
