### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by linchpinlin** [milvus-io/milvus-insight#209]
**Describe the bug:**
All Milvus-related components are installed on 192.168.240.3, but when l use it, I get the Network Error. I had tried localhost/127.0.0.1/192.168.240.3. I am sure my Milvus is working. Is there any log information for me to check?
![image](https://user-images.githubusercontent.com/31131753/128838838-b4179b97-2bb4-4b7c-b244-fe71990e6b0b.png)

**Steps to reproduce:**
1. 
![image](https://user-images.githubusercontent.com/31131753/128838472-bd4b7981-bc98-4263-adce-ddcf59733256.png)

![image](https://user-images.githubusercontent.com/31131753/128839854-df0e3d6c-4206-4d66-a129-27bbb9998a96.png)

2.
![image](https://user-images.githubusercontent.com/31131753/128838556-b80d3729-90c2-47f3-9352-00b0890e9f64.png)

**Milvus-insight version:**
![image](https://user-images.githubusercontent.com/31131753/128838635-77508e73-b948-42ab-9e04-badb7756aec0.png)

**Milvus version:**
 v2.0.0-rc2-20210712-a8e5fd2

**Comment by nameczz** [comment]
HOST_URL need to be you machine ip which run your milvus-insight docker.

If milvus-insight and milvus both running in 192.168.240.3. 

You can try: docker run -p 8000:3000 -e HOST_URL=http://192.168.240.3:8000 -e MILVUS_URL=192.168.240.3:19530 milvusdb/milvus-insight:latest

**Comment by nameczz** [comment]
Any more suggestions is welcome!
