### ISSUE TITLE
can not connect to milvus-proxy from milvus-insight

### ISSUE THREAD

**Issue by JamCrash** [milvus-io/milvus-insight#277]
### Discussed in https://github.com/milvus-io/milvus-insight/discussions/276

<div type='discussions-op-text'>

<sup>Originally posted by **JamCrash** January  6, 2022</sup>
My milvus-proxy and milvus-insight is deployed in the same k8s cluster, and the milvus-insight service is exposed using nodeport.
And my problem is that I can connect to insight from browser, but can not connect to proxy 

It shows like this:
![企业微信截图_16414602422370](https://user-images.githubusercontent.com/39126346/148358436-c51e8afd-bc11-411c-b8c7-30653fbff235.png)

And the insight pod logs:
![企业微信截图_16414603628149](https://user-images.githubusercontent.com/39126346/148358682-70e80847-90e4-4683-9555-d7fe66529f54.png)

</div>

**Comment by JamCrash** [comment]
@nameczz

**Comment by nameczz** [comment]
In your log, i can only find client static files request.  Could you please copy your docker run command for insight?

**Comment by Bennu-Li** [comment]
When you deploy Insight on k8s, how do you set the variable HOST_URL.
BTW, could you please provide the connection information displayed on the web page when you connect milvus proxy, and you can use F12 to get it.

**Comment by JamCrash** [comment]
> When you deploy Insight on k8s, how do you set the variable HOST_URL. BTW, could you please provide the connection information displayed on the web page when you connect milvus proxy, and you can use F12 to get it.

I deploy it with nodeport service, and configure a DNS record which maps the HOST_URL to IP
![企业微信截图_16415239302292](https://user-images.githubusercontent.com/39126346/148483756-f4767391-754f-49b9-8e3e-88b816275cdd.png)

@nameczz @Bennu-Li

**Comment by Bennu-Li** [comment]
And could you please copy the `yaml` file used to deploy insight.

**Comment by nameczz** [comment]
It's looks like  browser can not  connect to your HOST_URL, the request is send from browser , so please check your HOST_URL service is working in this network.

**Comment by JamCrash** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rc8-milvus-insight
  name: rc8-milvus-insight
  namespace: grey
spec:
  selector:
    matchLabels:
      app: rc8-milvus-insight
  template:
    metadata:
      labels:
        app: rc8-milvus-insight
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        - name: HOST_URL
          value: http://milvus-insight.ml.bigo.inner
        - name: MILVUS_URL
          value: http://rc8-milvus-proxy:19530
        image: milvusdb/milvus-insight:latest
        imagePullPolicy: Always
        name: insight
        ports:
        - containerPort: 3000
          name: insight
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rc8-milvus-insight
  name: rc8-milvus-insight
  namespace: grey
spec:
  ports:
  - name: insight
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30028
  selector:
    app: rc8-milvus-insight
  type: NodePort

**Comment by JamCrash** [comment]
[insight.zip](https://github.com/milvus-io/milvus-insight/files/7826056/insight.zip)
@Bennu-Li

**Comment by JamCrash** [comment]
> 

The brower is already load the login interface using HOST_URL

**Comment by JamCrash** [comment]
> It's looks like browser can not connect to your HOST_URL, the request is send from browser , so please check your HOST_URL service is working in this network.

The brower is already load the login interface using HOST_URL

**Comment by JamCrash** [comment]
does the url "rc8-milvus-proxy" in the connect page is using k8s DNS?

**Comment by JamCrash** [comment]
I connect to the insight out of the k8s cluster, and the milvus deployed in the k8s, so if the url "rc8-milvus-proxy" is sent to milvus-insight and using k8s DNS to resolve,  I think it should connect well normally

**Comment by Bennu-Li** [comment]
what is the url you visit the insigt on brower.

**Comment by JamCrash** [comment]
same as the HOST_URL
@Bennu-Li

**Comment by Bennu-Li** [comment]
1. Please ensure the milvus proxy is healthy. Try to describe the milvus-proxy service, make sure endpoints exist. 
<img width="1045" alt="截屏2022-01-07 上午11 58 47" src="https://user-images.githubusercontent.com/53458891/148489260-4304fcff-7892-42a6-872f-787464bc51fd.png">
2. Try replace  the milvus url with the milvus-proxy service CLUSTER_IP when connect to Milvus. 

Are the milvus proxy and insight in the same namespace?

**Comment by JamCrash** [comment]
the endpoints are running well, and they are in the same namespace

**Comment by JamCrash** [comment]
I think I find the reason why connect refused: 
The broswer send request using port 80 automatically, which is inconsistent with actual port 30028
![企业微信截图_16415285849375](https://user-images.githubusercontent.com/39126346/148490237-138e6d11-b600-44f2-b63e-adbef762d1ae.png)

**Comment by JamCrash** [comment]
change origin HOST_URL to HOST_URL:30028 fix this, thanks!
