### ISSUE TITLE
Maybe we should change the name 'Structure' to 'Column' 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#41]
Structure -> Columns
Add field -> Add column

is it more understandable？

**Comment by wu-yifan-design** [comment]
Hi! In my opinion, this suggestion does make it clearer in the table view interface, I just want to make sure that the concept of "structure" & "field" is still intact after we change it, is it still conceptually clear?
Ideas?

**Comment by shanghaikid** [comment]
@Tumao727 @nameczz what do you guys think?

**Comment by congtan0224** [comment]
halo, I prefer [structure],and [add column]

**Comment by shanghaikid** [comment]
The structure is consist of multiple columns only. 

I think "Columns" maybe a better word here.  @congtan0224 

![image](https://user-images.githubusercontent.com/185051/123029176-4a3e5c00-d413-11eb-974c-b376ff00fb42.png)
In create collection dialog,   we have two fixed columns, but there is no label telling user what are these. if we change "Define Structure" to "Define Columns", it is more obvious these two are columns.  

What do you think @congtan0224
