### ISSUE TITLE
Feature:  collection/partion filter

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-insight#45]
**Describe the feature:**
A quick filter that user can find his collection/partition easily.

**Comment by congtan0224** [comment]
Is that ok to add global search to the overall pages?

<img width="745" alt="Screen Shot 2021-06-28 at 11 53 04 AM" src="https://user-images.githubusercontent.com/77377414/123577991-72f59580-d807-11eb-9bd9-28faab1b0097.png">
<img width="536" alt="Screen Shot 2021-06-28 at 11 53 11 AM" src="https://user-images.githubusercontent.com/77377414/123577993-74bf5900-d807-11eb-8317-abfc81e81fe6.png">

**Comment by shanghaikid** [comment]
@congtan0224 I think we just want to add a search/filter bar in the collection/partition table.

**Comment by congtan0224** [comment]
Is [auto-fill] needed?
<img width="708" alt="Screen Shot 2021-06-28 at 4 00 57 PM" src="https://user-images.githubusercontent.com/77377414/123601255-08a21c80-d82a-11eb-89fe-8097309b53d0.png">

**Comment by congtan0224** [comment]
plan B, when type in character, the item in the table will be filtered and shown directly
<img width="790" alt="Screen Shot 2021-06-28 at 4 04 44 PM" src="https://user-images.githubusercontent.com/77377414/123601701-90882680-d82a-11eb-9c69-e1c3d1f68b13.png">

**Comment by shanghaikid** [comment]
We can discuss this issue in tomorrow's meeting.

**Comment by congtan0224** [comment]
If needed, design's here.
<img width="263" alt="Screen Shot 2021-06-29 at 2 35 16 PM" src="https://user-images.githubusercontent.com/77377414/123749142-ac9dcd80-d8e7-11eb-9f88-a9aa207e0bd6.png">
