### ISSUE TITLE
state should change to offline when no connection established

### ISSUE THREAD

**Issue by congtan0224** [milvus-io/milvus-insight#88]
<img width="351" alt="Screen Shot 2021-06-28 at 3 18 16 PM" src="https://user-images.githubusercontent.com/77377414/123596160-5ddb2f80-d824-11eb-8240-9d0aab8640a2.png">

**Comment by Tumao727** [comment]
This problem is not reproducible. Can you provide more details or steps to reproduce? @congtan0224
